catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from .apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home_page'),
    path('create_product/', views.ProductCreateView.as_view(), name='create_product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_confirm_delete'),
    path('detail/<int:pk>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_detail'),
    # path('contacts/', views.contact_page, name='contact_page'),
    path('blog/', views.BlogPostListView.as_view(), name='blogpost_list'),
    path('create/', views.BlogPostCreateView.as_view(), name='blog_create_post'),
    path('update/<int:pk>/', views.BlogPostUpdateView.as_view(), name='blogpost_update_form'),
    path('delete/<int:pk>/', views.BlogPostDeleteView.as_view(), name='blog_post_confirm_delete'),
    path('detail/<int:pk>/', views.BlogPostDetailView.as_view(), name='blog_post_detail'),
    path('redactor/<int:pk>/', views.BlogPostRedactorView.as_view(), name='blog_post_edit')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, verify

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verify/', verify, name='verify')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    phone = models.CharField(max_length=35, verbose_name='phone_number', null=True, blank=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='image', null=True, blank=True)
    country = models.CharField(max_length=50, verbose_name='Country', null=True, blank=True)
    code = models.CharField(unique=True, null=True, blank=True, verbose_name='secret_key')
    is_active = models.BooleanField("active",
                                    default=False,
                                    help_text=(
                                        "Designates whether this user should be treated as active. "
                                        "Unselect this instead of deleting accounts."
                                    ),
                                    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User
from catalog.forms import StyleFormMixin


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import secrets

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users import services
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            verification_code = secrets.token_urlsafe(nbytes=7)
            self.object.code = verification_code
            #
            # url = reverse('users:verification', args=[verification_code])
            # total_url = self.request.build_absolute_uri(url)
            # services.send_verification_url(total_url, self.object.email)
            send_mail(
                subject='verification code',
                message=f"There's a new code {verification_code}",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )
            self.object.save()

        return super().form_valid(form)

        #         instance.save()
        #     return super().form_valid(form)
        # send_mail(
        #     subject='You change your password',
        #     message=f"There's a new password {new_password}",
        #     from_email=settings.EMAIL_HOST_USER,
        #     recipient_list=[request.user.email]
        # )
        # return super().form_valid(form)


# class Verify(UpdateView):
#     model = User
#     template_name = 'users/verify.html'
#     success_url = 'catalog/home_page'
#
#     def form_valid(self, form):
#         if user.code == code:
#             user.is_active = True
#             user.save()
#
#     return render(request, 'users/verify.html')


def verify(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        if user.code == code:
            user.is_active = True
            user.save()
            return redirect(reverse('users:login'))
    return render(request, 'users/verify.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    services.send_new_password(request.user.email, new_password)
    # request.user.set_password(new_password)
    print(new_password)
    # request.user.save()
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Log in
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Log in</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Registration
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Registration</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Profile
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Save</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a>
                <a href="{% url 'users:generate_new_password' %}" type="button" class="btn btn-danger">Generate a new password</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/verify.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Verification
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" aria-describedby="email">
                </div>

                <div class="mb-3">
                    <label for="code" class="form-label">Code</label>
                    <input type="text" class="form-control" id="code" name="code"
                           aria-describedby="code">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Log in</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
        </div>
    </div>
</form>
{% endblock %}