catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from .apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home_page'),
    path('create_product/', views.ProductCreateView.as_view(), name='create_product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_confirm_delete'),
    path('detail/<int:pk>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_detail'),
    # path('contacts/', views.contact_page, name='contact_page'),
    path('blog/', views.BlogPostListView.as_view(), name='blogpost_list'),
    path('create/', views.BlogPostCreateView.as_view(), name='blog_create_post'),
    path('update/<int:pk>/', views.BlogPostUpdateView.as_view(), name='blogpost_update_form'),
    path('delete/<int:pk>/', views.BlogPostDeleteView.as_view(), name='blog_post_confirm_delete'),
    path('detail/<int:pk>/', views.BlogPostDetailView.as_view(), name='blog_post_detail'),
    path('redactor/<int:pk>/', views.BlogPostRedactorView.as_view(), name='blog_post_edit')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, verify

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verify/', verify, name='verify')
]

catalog/models.py
from django.db import models

from users.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    description = models.TextField(verbose_name='description')
    image = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='image')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='category')
    purchase_price = models.DecimalField(max_digits=8, decimal_places=2)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name='last_modified_date')
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Owner')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('last_modified_date', 'name',)


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='name')
    description = models.TextField(verbose_name='description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('name',)


class BlogPost(models.Model):
    title = models.CharField(max_length=255, verbose_name='header')
    slug = models.CharField(max_length=255, unique=True, verbose_name='slug')
    content = models.TextField(null=True, blank=True, verbose_name='content')
    preview = models.ImageField(upload_to='catalog/', null=True, blank=True, verbose_name='image')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')
    is_published = models.BooleanField(default=True, verbose_name='published')
    views_count = models.IntegerField(default=0, verbose_name='count_of_views')

    def __str__(self):
        return f'{self.title, self.views_count}'

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Product')
    version_number = models.PositiveSmallIntegerField(verbose_name='Number of version')
    version_name = models.CharField(max_length=100, verbose_name='Name of version')
    is_current = models.BooleanField(default=True, verbose_name='Active version')

    def __str__(self):
        return f"{self.version_name}: {self.version_number}, {self.is_current}"

    def save(self, *args, **kwargs):
        if self.is_current:
            Version.objects.filter(product=self.product, is_current=True).update(is_current=False)
        super(Version, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Version'
        verbose_name_plural = 'Versions'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_current':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    # Наследуемся от специального класса форм, который предоставляет
    # весь необходимый функционал, который нужно настроить
    black_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product  # Обязательно указываем модель
        exclude = ('date_of_creation ', 'last_modified_date')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         if field_name != 'is_current':
    #             field.widget.attrs['class'] = 'form-control'

    #         field.help_text = 'Some help text for field'

    def clean_name(self):

        cleaned_data = self.cleaned_data.get('name')

        for word in self.black_list:
            if word in cleaned_data:
                raise forms.ValidationError('Name of product has forbidden words!')

        return cleaned_data

    def clean_description(self):

        cleaned_data = self.cleaned_data.get('description')

        for word in self.black_list:
            if word in cleaned_data:
                raise forms.ValidationError('Description has forbidden words!')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         if field_name != 'is_current':
    #             field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, BlogPost, Version


class ProductListView(ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:create_product')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
    #     if self.request.method == 'POST':
    #         formset = VersionFormset(self.request.POST, instance=self.object)
    #     else:
    #         formset = VersionFormset(instance=self.object)
    #
    #     context_data['formset'] = formset
    #     return context_data
    #

    # def form_valid(self, form):
    #     context_data = self.get_context_data()
    #     formset = context_data['formset']
    #     self.object = form.save()
    #
    #     if formset.is_valid():
    #         formset.instance = self.object
    #         formset.save()
    #
    #     return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_update.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'

    # success_url = reverse_lazy('catalog:home_page')

    def get_success_url(self):
        return reverse('catalog:home_page', args=[self.kwargs.get('pk')])


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:home_page')


# def home_page(request):
#     context = {
#         'objects_list': Product.objects.all()
#     }
#     return render(request, 'catalog/product_list.html', context)


# def contact_page(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         message = request.POST.get('message')
#         print(f'{name} ({email}): {message}')
#     return render(request, 'catalog/contact_page.html')


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ['title', 'content', 'is_published']
    success_url = reverse_lazy('catalog:blogpost_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ['title', 'content', 'is_published']
    template_name = 'catalog/blogpost_update_form.html'
    success_url = reverse_lazy('catalog:blogpost_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    # def get_success_url(self):
    #     return reverse('catalog:blogpost_list', args=[self.kwargs.get('pk')])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'catalog/blog_post_confirm_delete.html'
    success_url = reverse_lazy('catalog:blogpost_list')


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'catalog/blog_post_detail.html'
    success_url = reverse_lazy('catalog:blogpost_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostRedactorView(DetailView):
    model = BlogPost
    template_name = 'catalog/blog_post_edit.html'
    success_url = reverse_lazy('catalog:blogpost_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'catalog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'catalog/css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Menu</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:home_page' %}" class="text-white">Main</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
            {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="text-black"><h3>Log out</h3></a>
            <a href="{% url 'users:profile' %}" class="text-black"><h3>Profile</h3></a>
            {% else %}
            <a href="{% url 'users:login' %}" class="text-black"><h3>Log in</h3></a>
            <a href="{% url 'users:register' %}" class="text-black"><h3>Registration</h3></a>
            {% endif %}
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; 2023.08 - {% now 'Y.m' %}</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<script src="{% static 'catalog/js/bootstrap.bundle.min.js' %}"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static 'catalog/js/popper.min.js' %}"></script>
<script src="{% static 'catalog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'catalog/js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_post_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Do you want to delete the blog </p>
    <h2>Name blog: {{ object.title }}</h2>
    <button type="submit" class="btn btn-warning">Delete</button>
    <a href="{% url 'catalog:blogpost_list' %}" type="submit" class="btn btn-warning">Reject</a>
</form>

{% endblock %}

catalog/templates/catalog/blog_post_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<h1>{{ object.title }}</h1>
<h1>{{ object.description }}</h1>
<h1>{{ object.content }}</h1>
Количество просмотров: {{ object.views_count }}
<a href="{% url 'catalog:blogpost_update_form' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Edit</a>
<a href="{% url 'catalog:blogpost_list'  %}" class="btn btn-lg btn-block btn-outline-primary">Back</a>
{% endblock %}

catalog/templates/catalog/blog_post_edit.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container bg-light rounded-3 p-3 overflow-hidden">

    <div class="container">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Edit Title</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                       placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Edit description</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-lg btn-block btn-outline-primary">Reject</a>
            <a href="{% url 'catalog:blog_post_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Confirm</a>
        </form>


        <h1>Views: {{ object.views_count }}</h1>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/blogpost_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button href="{% url 'catalog:blogpost_list' %}" type="submit" class="btn btn-success">Added blog</button>
</form>

{% endblock %}

catalog/templates/catalog/blogpost_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-4">
    <div class="card">
        <div class="card-head text-center">
            <h1>{{ object.title }}</h1>
        </div>
        <div class="card-body">
            {{ object.content }}

        </div>
        <div class="card-footer">
            <a href="{% url 'catalog:blog_post_detail' object.pk %}" type="button"
               class="btn btn-sm btn-success">Detail</a>
            <a href="{% url 'catalog:blog_create_post' %}" type="button"
               class="btn btn-sm btn-success">Create blog</a>
            <a href="{% url 'catalog:blog_post_confirm_delete' object.pk %}" type="button"
               class="btn btn-sm btn-success">Delete blog</a>

        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/blogpost_update_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button href="{% url 'catalog:blogpost_list' %}" type="submit" class="btn btn-success">Added blog</button>
</form>

{% endblock %}

catalog/templates/catalog/contact_page.html
{% extends  'catalog/base.html' %}
{% block content%}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Office Msk<br>
                Office Spb
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2>Write to us</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name"/>
                <input class="form-control mb-2" name="email"/>
                <textarea class="form-control mb-2" name="message"></textarea>
                <button type="submit" class="btn btn-primary form-control">Send</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header"><h2 class="card-title">
            Delete product
        </h2></div>

        <div class="card-body">
            Name of product: <h3>{{ object.name }}</h3>
            <hr>
            Description: <h4>{{ object.description }}</h4>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <hr>
                 <button type="submit" class="btn btn-danger">Delete</button>
            </form>

        </div>
        <div class="card-footer">

            <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">Name of product: <h2 class="card-title">
             {{ object.name }}
        </h2></div>

        <div class="card-body">
<!--          Description:  {{ object.description }}-->
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Description: {{ object.description|slice:":100" }}</li>
                {% for version_item in object.version_set.all %}
                {% if version_item.is_current %}
                <li> Version:  {{ version_item.version_name }}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="card-footer">
            <a href="{% url 'catalog:update_product' object.pk %}" type="button"
               class="btn btn-success">Edit</a>
            <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Add product
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Save</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Version
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}"> Add product </a>
    <a class="btn btn-outline-primary" href="{% url 'catalog:blogpost_list' %}"> Blog </a>
</div>
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <img src="{{ object.image|mymedia }}">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">$ {{ object.purchase_price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Description: {{ object.description|slice:":100" }}</li>
                {% for version in object.version_set.all %}
                <li> Version: {% if version.is_current %} {{ version.version_name }} {% else %} Не
                    задана {% endif %}
                </li>
                {% endfor %}
            </ul>
            <a href="{% url 'catalog:product_confirm_delete' object.pk %}" class="btn btn-lg btn-block btn-danger">Delete</a>
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Edit
                product</a>
            <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">View
                product</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header"><h2 class="card-title">
                Edit product
            </h2></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Save</button>
                <a href="{% url 'catalog:home_page' %}" type="button" class="btn btn-success">Back</a></div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Version
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}